version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./app:/app
      - ./cert:/app/cert    # ✅ Mount certs into backend
      - ./database:/app/database
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${APP_MODE}
      - APP_MODE=${APP_MODE}
    networks:
      - pong-network


networks:
  pong-network:
    driver: bridge
