
services:
  backend:
    build:
      context: .
      dockerfile: apps/Dockerfile
    container_name: app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./apps/:/app/
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${APP_MODE}
      - APP_MODE=${APP_MODE}
    networks:
      - pong-network



networks:
  pong-network:
    driver: bridge
