FROM node:24

WORKDIR /app

COPY ./apps/frontend ./
RUN mkdir -p /init
COPY ./scripts/init.sh /init/init.sh
RUN chmod +x /init/init.sh

EXPOSE 8080
# ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["/init/init.sh"]

