FROM node:24

WORKDIR /app

COPY ./apps/backend ./
RUN mkdir -p /init
COPY ./scripts/init.sh /init/init.sh
RUN chmod +x /init/init.sh

EXPOSE 3000
ENTRYPOINT ["tail", "-f", "/dev/null"]
CMD ["/init/init.sh"]
